# Generated by Django 4.1.5 on 2023-03-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_crypto',
            name='thumb',
            field=models.ImageField(blank=True, default='fhoto_tcnologyweb3.png', upload_to=''),
        ),
    ]
